### ISSUE TITLE
BUG | Minecraft 1.13.2下飞船飞不起来

### ISSUE THREAD

**Issue by Fangtang3** [Wenkrangha/BoatFly#18]
## 你在哪方面遇到了问题
在骑乘飞船时遇到问题
## 复现步骤
在Paper 1.13.2（657）下，飞船塞入燃料，按顺序按下键盘“1”键-“0”键多次，直到屏幕中出现“100%”
## 期望结果
飞船飞行
## 实际结果
飞船不会开始飞行
## 控制台报错
在com.wenkrang.boatfly.event.gui.OnEng(OnPlayer)处报NullPointerException

**Comment by Wenkrangha** [comment]
我们会在下一个版本周期修复

**Comment by Wenkrangha** [comment]
也许会（

**Comment by Wenkrangha** [comment]
我将在以后修复，现在不打算支持1.13.2
