### ISSUE TITLE
飞行控制面板的面板错误

### ISSUE THREAD

**Issue by znc15** [Wenkrangha/BoatFly#5]
![image](https://github.com/Wenkrangha/BoatFly/assets/64775575/f404a594-cda1-4920-a455-be77b6487b4f)
应该是飞行控制面板，而不是面包，已经提交了修改qwq

**Comment by Wenkrangha** [comment]
有没有一种可能，本来就叫飞行控制面包（
我之前觉得用控制面板台正经了qwq
就改成了面包（awa

**Comment by znc15** [comment]
> 有没有一种可能，本来就叫飞行控制面包（ 我之前觉得用控制面板台正经了qwq 就改成了面包（awa

草，那没事了（
