### ISSUE TITLE
Plugin do not work on paper-1.20.2-318

### ISSUE THREAD

**Issue by Lumine1909** [Wenkrangha/BoatFly#8]
Paper server won't sync boat entity's name to boat item's name when boat be created.
That will destroy the plugin.

![image](https://github.com/Wenkrangha/BoatFly/assets/133463833/afd89554-1588-4aca-a069-b1ba0e4e6a97)

(No custom name)
![image](https://github.com/Wenkrangha/BoatFly/assets/133463833/57a0dd97-c2d2-4e4e-8c6e-e2413ff6347f)

**Comment by Lumine1909** [comment]
I partially fix this problem by add [a listener](https://github.com/Lumine1909/BoatFly_Fix/blob/master/src/main/java/com/wenkrang/boatfly/event/VehicleCreate.java) and [register it](https://github.com/Lumine1909/BoatFly_Fix/blob/master/src/main/java/com/wenkrang/boatfly/Loader/LoadEvent.java), you can find all of the changes in my forked version.

**Comment by Wenkrangha** [comment]
是的，这个问题我在很久之前就发现了，但我的修复似乎没有用？

**Comment by Wenkrangha** [comment]
已解决
