### ISSUE TITLE
#8 is not fully fixed but marked as done

### ISSUE THREAD

**Issue by Lumine1909** [Wenkrangha/BoatFly#9]
#8 

![image](https://github.com/Wenkrangha/BoatFly/assets/133463833/521d3fc4-cc2d-4847-ab7f-c1548be298f2)
![image](https://github.com/Wenkrangha/BoatFly/assets/133463833/ea22cefc-20c1-476d-b128-8cd9a1eea398)
![image](https://github.com/Wenkrangha/BoatFly/assets/133463833/8cbd681b-6770-4c3c-ac0d-b933ecae857c)
![image](https://github.com/Wenkrangha/BoatFly/assets/133463833/185cb53a-c69c-4935-826f-f8d758bf125b)

**Comment by Lumine1909** [comment]
In addition, #6 also happened again (caused by not close inventory after kick player)

**Comment by Wenkrangha** [comment]
Ok,I see,I will fix it

**Comment by Wenkrangha** [comment]
But in many cases, errors do not impede the functioning of the plugin.

**Comment by Wenkrangha** [comment]
已解决，版本更新1.5.3a
